create_certs_tool = /usr/bin/swtpm_localca
create_certs_tool_config = ${XDG_CONFIG_HOME}/swtpm-localca.conf
create_certs_tool_options = ${XDG_CONFIG_HOME}/swtpm-localca.options
# Comma-separated list (no spaces) of PCR banks to activate by default
active_pcr_banks = sha256

# profile_file =
local_profiles_dir = /etc/swtpm/profiles/
